version: 0.2

env:
  variables:
    AWS_REGION: "ap-south-2"
    ECR_REPOSITORY_NAME: "employee-directory"
    IMAGE_TAG: "latest"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REPOSITORY_URI=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_NAME
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - echo Repository URI is $REPOSITORY_URI

  build:
    commands:
      - echo Build started on `date`
      - echo Building Docker image...
      - docker build -t $ECR_REPOSITORY_NAME:$IMAGE_TAG ./employee-directory
      - docker tag $ECR_REPOSITORY_NAME:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing Docker image to Amazon ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Image pushed successfully
      - printf '[{"name":"employee-directory-container","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

      - echo Triggering ECS deployment...
      - aws ecs update-service --cluster employee-directory-cluster --service employee-directory-service --force-new-deployment --region ap-south-2

artifacts:
  files:
    - imagedefinitions.json