spring.application.name=employee-directory
server.port=8080spring.application.name=employee-directory
server.port=8080

aws.region=${AWS_REGION_NAME:ap-south-2}
aws.dynamodb.table-name=${DYNAMODB_TABLE_NAME:employee-directory-table}